#!/bin/sh
set -e

case "$1" in
    configure)
      udevDependent=`which udisks 2> /dev/null` # Ubuntu, Mint
      if [ -z "$udevDependent" ]
      then
          udevDependent=`which systemd 2> /dev/null` # Fedora, SUSE
      fi
      if [ -z "$udevDependent" ]
      then
          udevDependent=`which findmnt` # Arch
      fi
      udevso=`ldd $udevDependent | grep libudev.so | awk '{print $3;}'`
      if [ -e "$udevso" ]; then
         ln -sf "$udevso" /usr/share/gdrush/libudev.so.0
      fi
    ;;

    abort-upgrade|abort-remove|abort-deconfigure)
      exit 0
    ;;

    *)
      echo "postinst called with unknown argument \`$1'" >&2
      exit 0
    ;;
esac

#DEBHELPER#

exit 0
